version: "3.8"

services:
  quartpostgresapp-service:
    build:
      context: .
    ports:
      - "5000:5000"
    tty: true
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
    restart: always
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
