version: "3.8"

services:
  quartpostgresapp-service:
    build:
      context: .
    ports:
      - "5008:5008"
    tty: true
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
  database:
    image: postgres
    restart: always
    environment:
      POSTRGRES_PASSWORD: password
