version: "3.8"

volumes:
  aiohttp_app:
  quart_postgres_app:

services:
  # quart_app
  quart_app-service:
    container_name: quart_app
    build:
      context: ./quart_app
    ports:
      - "5007:5007"
    volumes:
      - quart_app:/quart_app
    restart: always

  # quart_postgres_app
  quart_postgres_app-service:
    build:
      context: ./quart_postgres_app
    ports:
      - "5008:5008"
    volumes:
      - quart_postgres_app:/quart_postgres_app
    tty: true
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
    restart: always
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password