# prometheus.yml
---
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'database-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['aiohttp_app-service:5000']
        labels:
          group: 'database-test'
