version: "3.8"

services:

  # quart_postgres_app
  quart_postgres_app-service:
    build:
      context: .
    ports:
      - "5008:5008"
    tty: true
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
    restart: always
    depends_on:
      - database

  # postgres
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  # pgadmin4
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 12345