version: "3.8"

services:
  quart_postgres_app-service:
    build:
      context: .
    ports:
      - "5008:5008"
    tty: true
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
    restart: always
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password